services:
    backend:
        restart: always
        build:
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            - MONGO_URL=mongodb
            - MONGO_USERNAME=dni
            - MONGO_PASSWORD=dni@123
        depends_on: [mongodb]
        
    mongodb:
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: dni
            MONGO_INITDB_ROOT_PASSWORD: dni@123
        volumes:
            - ./.volume:/data/db

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
