### home page
GET http://0.0.0.0:8080

### list todos
GET http://0.0.0.0:8080/todos

### get todo
GET http://0.0.0.0:8080/todos/65efc34c82e5aa261a76bbd2

### insert todo
POST http://0.0.0.0:8080/todos
Content-Type: application/json

{
    "title": "Need to write the Rust Code",
    "content": "From today, I need to write the Rust code for 2 hours daily. ",
    "status": "Open"
}


### update todo
PUT http://0.0.0.0:8080/todos/65ef390b55f2e84700ac9abd
Content-Type: application/json

{
    "title": "Fourth Todo Modified",
    "content": "This is the Fourth todo modified",
    "status": "Doing",
    "date": "Tue, 12 Mar 2024 02:21:23 GMT"
}

### delete todo
DELETE http://0.0.0.0:8080/todos/65efbbfba7bcf2a5adc72803
