### home page
GET http://0.0.0.0:8080

### list todos
GET http://0.0.0.0:8080/todos

### get todo
GET http://0.0.0.0:8080/todos/65f1ba0f09e9bd4efa370695

### insert todo
POST http://0.0.0.0:8080/todos
Content-Type: application/json

{
    "title": "Title two",
    "content": "This is the title 2",
    "status": "Open"
}


### update todo
PUT http://0.0.0.0:8080/todos/65f1ba0f09e9bd4efa370695
Content-Type: application/json

{
    "title": "Title One Modified",
    "content": "This is the title 1",
    "status": "Doing",
    "date": "2024-03-13 14:37:03"
}

### delete todo
DELETE http://0.0.0.0:8080/todos/65f1ba6309e9bd4efa37069f
